export const STATUS_LABELS: Record<string, string> = {
  lead: 'Lead',
  opp_created: 'OPP Created',
  survey_scheduled: 'Survey Scheduled',
  survey_completed: 'Survey Completed',
  design_in_progress: 'Design In Progress',
  design_completed: 'Design Completed',
  rfp_sent: 'RFP Sent',
  ready_for_quoting: 'Ready for Quoting',
  quote_pending_approval: 'Quote Pending Approval',
  quote_approved: 'Quote Approved',
  quote_declined: 'Quote Declined',
  customer_review: 'Customer Review',
  customer_approved: 'Customer Approved',
  customer_declined: 'Customer Declined',
  awaiting_po: 'Awaiting PO',
  po_received: 'PO Received',
  ready_for_project: 'Ready for Project',
  project_active: 'Project Active',
  installation: 'Installation',
  qc_in_progress: 'QC In Progress',
  qc_complete: 'QC Complete',
  closeout: 'Closeout',
  closed_won: 'Closed Won',
  closed_lost: 'Closed Lost',
};

export const STATUS_COLORS: Record<string, string> = {
  lead: 'bg-gray-100 text-gray-700',
  opp_created: 'bg-blue-100 text-blue-700',
  survey_scheduled: 'bg-purple-100 text-purple-700',
  survey_completed: 'bg-purple-200 text-purple-800',
  design_in_progress: 'bg-indigo-100 text-indigo-700',
  design_completed: 'bg-indigo-200 text-indigo-800',
  rfp_sent: 'bg-orange-100 text-orange-700',
  ready_for_quoting: 'bg-yellow-100 text-yellow-800',
  quote_pending_approval: 'bg-amber-100 text-amber-800',
  quote_approved: 'bg-green-100 text-green-700',
  quote_declined: 'bg-red-100 text-red-700',
  customer_review: 'bg-cyan-100 text-cyan-700',
  customer_approved: 'bg-green-200 text-green-800',
  customer_declined: 'bg-red-200 text-red-800',
  awaiting_po: 'bg-yellow-200 text-yellow-800',
  po_received: 'bg-green-100 text-green-700',
  ready_for_project: 'bg-teal-100 text-teal-700',
  project_active: 'bg-blue-200 text-blue-800',
  installation: 'bg-sky-100 text-sky-700',
  qc_in_progress: 'bg-violet-100 text-violet-700',
  qc_complete: 'bg-emerald-100 text-emerald-700',
  closeout: 'bg-emerald-200 text-emerald-800',
  closed_won: 'bg-green-300 text-green-900',
  closed_lost: 'bg-gray-200 text-gray-600',
};
